# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cacctl < Formula
  desc ""
  homepage ""
  version "0.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hef/cacctl/releases/download/v0.5.2/cacctl_0.5.2_Darwin_x86_64.tar.gz"
      sha256 "0d9c24e7f0ccfc06931c32ee9678b818645866b8347a14bae372cd6d353e2ff0"

      def install
        bin.install "cacctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hef/cacctl/releases/download/v0.5.2/cacctl_0.5.2_Darwin_arm64.tar.gz"
      sha256 "84b0ed33c7bf328b73f58bcb2f33c3d625630f4a20935bdd35e9913008627146"

      def install
        bin.install "cacctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hef/cacctl/releases/download/v0.5.2/cacctl_0.5.2_Linux_x86_64.tar.gz"
      sha256 "9d8db9fa3fc21c6335ff90a3687f27dc05ba45cfccd0e97b3b123078f4d6769e"

      def install
        bin.install "cacctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hef/cacctl/releases/download/v0.5.2/cacctl_0.5.2_Linux_arm64.tar.gz"
      sha256 "b04250b235d4173956ca68ed99058576439d6d3554428b8efe2348fa5ff9261b"

      def install
        bin.install "cacctl"
      end
    end
  end
end
